server:
  port: 8084

spring:
  application:
    name: CLOUD-GATEWAY
  cloud:
    gateway:
          routes:
            - id: -EMPLOYEE-SERVICE
              uri: lb://EMPLOYEE-SERVICE
              predicates:
                - Path=/employee/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: EMPLOYEE-SERVICE
                    fallbackuri: forward:/employeeServiceFallBackMethod

            - id: ADDRESS-SERVICE
              uri: lb://ADDRESS-SERVICE
              predicates:
                - Path=/address/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: ADDRESS-SERVICE
                    fallbackuri: forward:/addressServiceFallBackMethod


hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2500

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream